#!/usr/bin/env bash
# This script groups Apache log data by IP and HTTP code and counts occurrences

awk '{count[$1" "$9]++} END {for (key in count) print count[key], key}' apache-access.log | sort -nr
#!/usr/bin/env bash
# This script groups Apache log data by IP and HTTP code and counts occurrences

awk '{count[$1" "$9]++} END {for (key in count) print count[key], key}' apache-access.log | sort -nr
