#!/usr/bin/env bash
# Prints "To infinity and beyond" indefinitely, reacts to SIGTERM

# Trap SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop with sleep 2
while true; do
    echo "To infinity and beyond"
    sleep 2
done
